"""initial schema

Revision ID: b88345d07a98
Revises: 
Create Date: 2026-08-22 12:47:27.973493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b88345d07a98'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_parent_id'), 'categories', ['parent_id'], unique=False)
    op.create_table('character_knowledge',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('learner_id', sa.String(length=36), nullable=False),
    sa.Column('character_literal', sa.String(length=10), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'LEARNING', 'KNOWN', name='knowledgestatus'), nullable=False),
    sa.Column('successful_recognitions', sa.Integer(), nullable=False),
    sa.Column('failed_recognitions', sa.Integer(), nullable=False),
    sa.Column('correct_pinyin_count', sa.Integer(), nullable=False),
    sa.Column('times_seen', sa.Integer(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_practised_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_review_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('learner_id', 'character_literal', name='uq_learner_character')
    )
    op.create_index(op.f('ix_character_knowledge_learner_id'), 'character_knowledge', ['learner_id'], unique=False)
    op.create_index(op.f('ix_character_knowledge_next_review_at'), 'character_knowledge', ['next_review_at'], unique=False)
    op.create_table('characters',
    sa.Column('symbol', sa.String(length=1), nullable=False),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_table('sentences',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('tokens_json', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sentences_raw_text'), 'sentences', ['raw_text'], unique=False)
    op.create_table('tokens',
    sa.Column('text', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('text')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('vocabulary_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('text', sa.String(length=255), nullable=False),
    sa.Column('pinyin', sa.String(length=255), nullable=False),
    sa.Column('meaning', sa.String(length=512), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vocabulary_items_text'), 'vocabulary_items', ['text'], unique=False)
    op.create_table('vocabulary_knowledge',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('learner_id', sa.String(length=36), nullable=False),
    sa.Column('vocabulary_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'LEARNING', 'KNOWN', name='knowledgestatus'), nullable=False),
    sa.Column('successful_recalls', sa.Integer(), nullable=False),
    sa.Column('failed_recalls', sa.Integer(), nullable=False),
    sa.Column('times_seen', sa.Integer(), nullable=False),
    sa.Column('times_produced', sa.Integer(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_practised_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_review_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ease_factor', sa.Float(), nullable=True),
    sa.Column('interval_days', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('learner_id', 'vocabulary_id', name='uq_learner_vocab')
    )
    op.create_index(op.f('ix_vocabulary_knowledge_learner_id'), 'vocabulary_knowledge', ['learner_id'], unique=False)
    op.create_index(op.f('ix_vocabulary_knowledge_next_review_at'), 'vocabulary_knowledge', ['next_review_at'], unique=False)
    op.create_table('category_assignments',
    sa.Column('category_id', sa.String(length=36), nullable=False),
    sa.Column('vocabulary_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['vocabulary_id'], ['vocabulary_items.id'], ),
    sa.PrimaryKeyConstraint('category_id', 'vocabulary_id'),
    sa.UniqueConstraint('category_id', 'vocabulary_id', name='uq_category_vocabulary')
    )
    op.create_table('learner_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('language', sa.String(length=20), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learner_profiles_user_id'), 'learner_profiles', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_learner_profiles_user_id'), table_name='learner_profiles')
    op.drop_table('learner_profiles')
    op.drop_table('category_assignments')
    op.drop_index(op.f('ix_vocabulary_knowledge_next_review_at'), table_name='vocabulary_knowledge')
    op.drop_index(op.f('ix_vocabulary_knowledge_learner_id'), table_name='vocabulary_knowledge')
    op.drop_table('vocabulary_knowledge')
    op.drop_index(op.f('ix_vocabulary_items_text'), table_name='vocabulary_items')
    op.drop_table('vocabulary_items')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('tokens')
    op.drop_index(op.f('ix_sentences_raw_text'), table_name='sentences')
    op.drop_table('sentences')
    op.drop_table('characters')
    op.drop_index(op.f('ix_character_knowledge_next_review_at'), table_name='character_knowledge')
    op.drop_index(op.f('ix_character_knowledge_learner_id'), table_name='character_knowledge')
    op.drop_table('character_knowledge')
    op.drop_index(op.f('ix_categories_parent_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
