"""changed_vocab_meaning_to_text

Revision ID: c7b0dbb4e34c
Revises: e05484f9fbee
Create Date: 2026-08-23 19:29:22.634772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7b0dbb4e34c'
down_revision: Union[str, Sequence[str], None] = 'e05484f9fbee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_unique_constraint('uq_category_vocabulary', 'category_assignments', ['category_id', 'vocabulary_id'])
    op.alter_column('vocabulary_items', 'meaning',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.Text(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vocabulary_items', 'meaning',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=512),
               existing_nullable=False)
    op.drop_constraint('uq_category_vocabulary', 'category_assignments', type_='unique')
    # ### end Alembic commands ###
